'''
Python regression function module generated by Evogression.
'''

def regression_func(parameters: dict) -> float:
    '''Generated by an Evogression creature'''

    # No input parameters used for regression    T = 0  # T is the value from the previous layer if multiple layers
    T = 0  # T is the value from the previous layer if multiple layers

    # LAYER_1
    T += 0.7087
    T += -0.579 * (0.1739 * parameters['clump_thickness'] + 0.0732) ** 1.0
    T += -0.1267 * (-0.0451 * parameters['marginal_adhesion'] + 0.0862) ** 2.0
    T += 0.3706 * (0.0 * parameters['normal_nucleoli'] + -0.1566) ** 1.0
    T += -0.1431 * (-0.6119 * parameters['uniformity_of_cell_shape'] + 0.0486) ** 2.0
    previous_T, T = T, 0

    # LAYER_2
    T += 0.3858
    T += 0.637 * (-0.1729 * previous_T + -0.5664) ** 2.0
    T += 0.7344 * (0.1755 * parameters['bare_nuclei'] + 0.0005) ** 2.0
    T += -0.1779 * (0.1255 * parameters['single_epithelial_cell_size'] + 0.0322) ** 2.0

    return T
